apiVersion: v1
kind: Service
metadata:
  name: migration
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: migration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      serviceAccountName: ds-admin
      containers:
        - name: migration
          image: 'appveen/datanimbus.io.migration:2.7.5'
          ports:
            - containerPort: 3000
          envFrom:
          - configMapRef:
              name: config